<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/EasyTierHost.Service/EasyTierHost.Service.csproj" />
    <ProjectReference Include="../../src/EasyTierHost.Deployment/EasyTierHost.Deployment.csproj" />
  </ItemGroup>
</Project>
